org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod
mod_id=mightyghast
mod_name=Mighty Ghast
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.nakanaka.mightyghast
mod_authors=nakanaka
mod_description=Ghasts become Wither-tier bosses, drop Ghast Ingots, and the Ghast Blade unleashes their techniques.
